### ISSUE TITLE
Tech Stack ?

### ISSUE THREAD

**Issue by Satyampatil513** [Satyampatil513/Cansat-Ground-Control-System-24-25#1]
22-23 - C# (visual Studio) 
23-24 - python (pyqt)

Python final

Deepansha - PyQt5 Tkinter
Satyam - Kivy
wxPython
Bhumesh -Libavg
PySimpleGUI

**Comment by Satyampatil513** [comment]
Serial Port connection
Gui Easability
Data Representation

**Comment by Satyampatil513** [comment]
**Kivy:**
**Advantages:**
1. Has Good community
2. KvLang can help in some features, but again I think python will take care of most of the things
**Disadvantages:**
1. Cross-platform Framework -  Runs on Android, Linux, WIndows, Ios { we done need that}
2. Uses its own language - we also dont need that
3. Uses its own- Graphic Engine - we also done need that
4. it’s arguably harder to integrate with desktop environments (contextual menus, multiple windows, etc, are not features kivy are friendly to.

**Comment by deepanshadeora** [comment]
PYQT5
**advantages:**
1. easy integration
2. Asynchronous Support
3. wide range of built-in widgets
4. PyQt5 integrates well with libraries like Matplotlib and PyQtGraph
**disadvantages:**
1.cross -platform framework
2.Handling large datasets in PyQt5 can lead to performance issues if not optimized properly.
3.resource intensive.
4. requiring a lot of boilerplate code for even simple tasks, which can slow down development.
5. a bit complex to setup serial communication.

**Comment by deepanshadeora** [comment]
Tkinter
**advantages**
1.simpler and more straightforward API.

**disadvantages**
1.requires more manual management of threads
2.limited set of widgets 
3.limited built-in support for advanced data representation.
4.less suitable for large-scale or highly complex applications

**Comment by BlackDevil559** [comment]
libavg with PySerial:- 
**Advantages**
- uses python as scripting language, is written in high-speed C++ and uses modern OpenGL for display output.

**Disadvantages**
- less common for such applications and might require more custom handling.
- for real-time serial data display and transmission, PyQt5/PySide2 or Tkinter are generally more straightforward and better supported options.

**Comment by BlackDevil559** [comment]
PySimpleGUI 5.0.6:-
- Easy and multi-page functioning is quit good!
- The variety of widgets and controls available in PySimpleGUI is less extensive compared to frameworks like PyQt5 or GTK.
(Will not be using)

**Comment by BlackDevil559** [comment]
What is suggested finally?
@Satyampatil513 and @deepanshadeora 
I am support with PyQT5. It has own UI dashboard and has wide range of online documentation.

**Comment by Satyampatil513** [comment]
Agreed
